import turtle
def draw_squre():
    window=turtle.Screen()
    window.bgcolor('red')
    john=turtle.Turtle()
    john.shape('turtle')
    john.color('green')
    john.speed(5)
    john.forward(150)
    john.right(90)
    john.forward(150)
    john.right(90)
    john.forward(150)
    john.right(90)
    john.forward(150)
    window.exitonclick()
draw_squre()